name: 'Form Data Processor'
description: 'Form Data Processor'
inputs:
  google-sa-email:
    description: 'Google SA Email'
    required: true
  google-sa-pk:
    description: 'Google SA Private Key'
    required: true
outputs:
  processing-result:
    description: 'Result of processing'
runs:
  using: 'node16'
  main: 'index.js'
