name: 'Form Data Processor'
description: 'Form Data Processor'
inputs:
  google-sa-email:
    description: 'Google SA Email'
    required: true
  google-sa-pk:
    description: 'Google SA Private Key'
    required: true
  google-sheet-id:
    description: 'Google Spreadsheet ID'
    required: true
  sheet-status-column:
    description: 'Name of status column in sheet'
    required: true
    default: 'ProcessingStatus'
  sheet-error-column:
    description: 'Name of error message column in sheet'
    required: true
    default: 'ErrorMessage'
  sf-instance-url:
    description: 'Salesforce Instance URL'
    required: true
  sf-client-id:
    description: 'Salesforce Client ID'
    required: true
  sf-client-secret:
    description: 'Salesforce Client Secret'
    required: true
  sf-version:
    description: 'Salesforce Version'
    required: true
  sf-type:
    description: 'Salesforce Object Type'
    required: true
  form-to-sf-mapping:
    description: 'Form to SalesForce field mapping'
    required: true
outputs:
  processing-result:
    description: 'Result of processing'
runs:
  using: 'node16'
  main: 'index.js'
