name: 'Form Data Processor'
description: 'Form Data Processor'
inputs:
  ms-graph-auth-token:
    description: 'MS Graph Access Token'
    required: true
  sf-instance-url:
    description: 'Salesforce Instance URL'
    required: true
  sf-client-id:
    description: 'Salesforce Client ID'
    required: true
  sf-client-secret:
    description: 'Salesforce Client Secret'
    required: true
  default-settings:
    description: 'Default settings'
    required: true
    default: '{"SFMappingSheet": "helix-default", "FormFieldNameColumn": "Name", "IncomingStatusColumn": "ProcessingStatus", "IncomingErrorMsgColumn": "ErrorMessage"}'
outputs:
  processing-result:
    description: 'Result of processing'
runs:
  using: 'node16'
  main: 'index.js'
