name: 'Form Data Processor'
description: 'Form Data Processor'
inputs:
  google-sa-email:
    description: 'Google SA Email'
    required: true
  google-sa-pk:
    description: 'Google SA Private Key'
    required: true
  google-sheet-id:
    description: 'Google Spreadsheet ID'
    required: true
  sf-instance-url:
    description: 'Salesforce Instance URL'
    required: true
  sf-client-id:
    description: 'Salesforce Client ID'
    required: true
  sf-client-secret:
    description: 'Salesforce Client Secret'
    required: true
  default-settings:
    description: 'Default settings'
    required: true
    default: '{"SFMappingSheet": "helix-default", "FormFieldNameColumn": "Name", "IncomingStatusColumn": "ProcessingStatus", "IncomingErrorMsgColumn": "ErrorMessage"}'
outputs:
  processing-result:
    description: 'Result of processing'
runs:
  using: 'node16'
  main: 'index.js'
