name: 'Form Data Processor'
description: 'Form Data Processor'
inputs:
  repo-owner-name:
    description: 'Repository owner and name'
    required: true
  repo-key-id:
    description: 'Repository public key ID'
    required: true
  repo-key:
    description: 'Repository public key'
    required: true
  repo-token:
    description: 'Repository bearer token'
    required: true
  repo-msal-cache-dump-secret:
    description: 'Repository secret name for MSAL token cache dump'
    required: true
    default: 'MSAL_CACHE_DUMP'
  ms-graph-tenant:
    description: 'MS Graph tenant ID'
    required: true
  ms-graph-refresh-token:
    description: 'MS Graph refresh token'
    required: true
  ms-graph-client-id:
    description: 'MS Graph client ID'
    required: true
  ms-graph-client-secret:
    description: 'MS Graph client secret'
    required: true
  ms-graph-scope:
    description: 'MS Graph token scope'
    required: true
    default: 'offline_access Files.ReadWrite'
  max-rows:
    description: 'Max rows to be processed'
    required: true
    default: '-1'
  msal-cache-dump:
    description: 'MSAL token cache dump'
    required: true
  sf-instance-url:
    description: 'Salesforce Instance URL'
    required: true
  sf-client-id:
    description: 'Salesforce Client ID'
    required: true
  sf-client-secret:
    description: 'Salesforce Client Secret'
    required: true
  default-settings:
    description: 'Default settings'
    required: true
    default: '{"SFMappingSheet": "helix-default", "FormFieldNameColumn": "Name", "IncomingStatusColumn": "ProcessingStatus", "IncomingErrorMsgColumn": "ErrorMessage"}'
outputs:
  processing-result:
    description: 'Result of processing'
runs:
  using: 'node16'
  main: 'index.js'
